### ISSUE TITLE
sign releases

### ISSUE THREAD

**Issue by dankamongmen** [libsixel/libsixel#14]
many distros would prefer that we sign our releases with some known key. @ctrlcctrlv , are you opposed to this? if not, i'll make a new keypair and share it with you, and write up a little release script that signs the tarball and uploads it to github's archive section.

**Comment by ctrlcctrlv** [comment]
Not opposed. I can sign with GnuPG key `6F12 EC72 A82A BCA3 5235 063A 10DD C983 901A A183`, which is a personal key I've had for many years. If you want to sign releases sometimes too, a shared key may be better.

**Comment by dankamongmen** [comment]
I've created a release script at `tools/release` (branch `dankamongmen/release`). This takes care of tagging the tree, downloading the archive from github, signing it, uploading the signature, and cutting a version.

**Comment by dankamongmen** [comment]
https://github.com/libsixel/libsixel/releases/tag/v1.10.2 was just cut, and is the first release to be signed.
