### ISSUE TITLE
Overhaul of README / check for wrong or broken links

### ISSUE THREAD

**Issue by schrmh** [libsixel/libsixel#17]
The reason I'm creating this issue is that e.g. the link to my project in the README is broken (it always was broken but I thought that it might be fixed by saitoha when he adds new links.. but in the end it was never fixed).
Link is https://github.com/libsixel/libsixel/blob/master/schrmh/pdfgrepSIXEL in README but should be https://github.com/schrmh/pdfgrepSIXEL.
Maybe take this as an opportunity to check other things within the README. E.g. in the contribution section it still says that you should fork https://github.com/saitoha/libsixel/fork/.

**Comment by dankamongmen** [comment]
I've updated the link to pdfgrepSIXEL.

I've updated all "http:" instances to "https:".

I'm running w3c-linkchecker on the result as we speak.

**Comment by dankamongmen** [comment]
Updated contributing link, added @ctrlcctrlv and myself as contributors, and added a notcurses link to the "other software supporting sixel" section, because I wasn't using this new comaintainership to self-aggrandize nearly enough.

**Comment by dankamongmen** [comment]
￼ Line: 1357 https://bitbucket.org/arakiken/w3m/branch/remoteimg
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 1378 https://bitbucket.org/arakiken/mikutterm/branch/sixel
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 1379 https://bitbucket.org/arakiken/mikutterm
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Lines: 877, 917 https://github.com/libsixel/libsixel/blob/%7B%7B%20urlEncodedRefName%20%7D%7D/README.md
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 2956 https://itunes.apple.com/jp/app/graphicconverter-9/id736099092?mt=12 redirected to https://apps.apple.com/jp/app/graphicconverter-9/id736099092?mt=12
Status: 301 -> 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 3064 https://github.com/libsixel/libsixel/blob/master/schrmh/pdfgrepSIXEL
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Lines: 1385, 1386, 2864 https://bitbucket.org/arakiken/tw/branch/sixel
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 2998 https://github.com/lesnitsky/sixel-decoder
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 1368 https://bitbucket.org/arakiken/screen/branch/sixel
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 2868 https://github.com/isaki68k/sayaka/blob/master/vala/sixelv.vala
Status: 404 Not Found
The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link.

￼ Line: 14 https://user-images.githubusercontent.com/
Status: 403 Forbidden
The link is forbidden! This needs fixing. Usual suspects: a missing index.html or Overview.html, or a missing ACL.

￼ Line: 1404 https://github.com/dylanaraps/neofetch/wiki/Image-Backends
Status: 200 OK
Some of the links to this resource point to broken URI fragments (such as index.html#fragment).

Broken fragments:
https://github.com/dylanaraps/neofetch/wiki/Image-Backends#sixel (line 1404)

**Comment by ctrlcctrlv** [comment]
In my opinion the README is ridiculously long and a lot of the content should be split into a wiki or other files in a new `doc` directory. Compare to [FontForge's README](https://github.com/fontforge/fontforge).

**Comment by dankamongmen** [comment]
> In my opinion the README is ridiculously long and a lot of the content should be split into a wiki or other files in a new `doc` directory. Compare to [FontForge's README](https://github.com/fontforge/fontforge).

yes

**Comment by schrmh** [comment]
I guess @saitoha kept adding each useful SIXEL project so that people could immediately see how useful it is (*scroll down* → "WOW" reaction → "I wan't to try that out").
So maybe keep in mind before removing or moving stuff to other places that it might hurt adoption. The goal should not be that the README is extramly short but that it's "comfortable" (fyi saitoha was active on the suckless community in the past — he even links to that in the 24bit color issue — that is against bloated software so I'm pretty sure that he put some thought into the README).
There are definitly some technical things that can be moved elsewhere or hidden. You can alsways hide stuff with some simple HTML like this:
```
<details><summary><b>Example title</b></summary>
<p>  

</p>
</details>
```


PS: I dislike that the mentioned FontForge README has no picture of the GUI. You could argue that some people don't have the bandwidth to download bigger images but tbh if people want to see the GUI they either have to download the whole project or to go to the website which would both definitly take more resources than a simple image (that might be delivered at a low resolution and then loads more afterwards e.g. in case of newer image formats like JXL)

**Comment by ctrlcctrlv** [comment]
I understand what you mean about "scroll down → WOW". I tried to do something similar for [MFEK/stroke](https://github.com/MFEK/stroke)'s README, a project I founded.

I also started [MFEK/glif](https://github.com/MFEK/glif), which is like FontForge, and agree with you an app like that should have a screenshot.

With that said, I'd say this project is closer to MFEK/stroke than to either FontForge or MFEKglif. A lot of the images are useful, yes. However, full copies of every license statement and large chunks of C code are not and should be split off I think.

**Comment by schrmh** [comment]
Yeah. Technical thinks like the things you mentioned can be moved to a wiki page or maybe be removed. A lot of the API stuff might be moveable to a wiki page.
"Usage of command line tools" section is something that can be partly moved to the end of the README or to a wiki page. You could also hide things like img2sixel options with some HTML so that people don't need to switch sites but only need to click once to see them. 

I guess I will keep this issue open and when you are done with an overhaul of the README and you consider it at a comfortable state then feel free to close it.

**Comment by ctrlcctrlv** [comment]
I also drew some pixel art to be the organization's icon. It should probably be in the README as well.

![image](https://user-images.githubusercontent.com/838783/121893387-e8cc0e00-cceb-11eb-9874-50798f87bc87.png)

**Comment by schrmh** [comment]
@ctrlcctrlv If you really want to include the organization icon into the README then I would say at the end of it together with maybe two sentences about the organization or its goal (with libsixel or in general). 

(will get a bit of off-topic now:)
Also since there is an older monitor on your icon.. SIXEL is old but has in my opinion a big potential on newer systems. We should strive for more adoptions on those while keeping compatibility and maybe you can represent that somehow in the icon. 
(A bit OT: When it comes to the major problems that might hinder adoption then the number one problem is IMO that each terminal emulator has different problems that you can easily experience when it comes to their SIXEL implementation; e.g. st-sixel is the best TE for my project cause that's the only one that doesn't remove SIXEL images if you output "too many" while xterm removes them after 16 and mltearm after a few more. But st-sixel always displays two times the same images next to each other.. Another example: The drawing demo only seems to work for me with xterm and only when that is big enough.. Also I'm not sure whether it is possible to redraw on the same area using SIXEL without scrolling the terminal down.. So my project is basically on hold cause I can't implement zooming yet — would at least need to get either some coordinates or info on which image the user clicked). 

The only real competitor to SIXEL that is still alive and that I am aware of is the stuff that the kitty terminal emulator uses. And that looks really amazing but is only limited to that terminal emulator and has no backwards compatibility at all as I am aware of. Courses, terminfo and such stuff are not really competitors I would say.


**Ah, maybe also think about creating and add a link to some IRC or Matrix community so that people could discuss a bit about SIXEL (so they don't need to spam issues.. Lol).**

**Comment by ctrlcctrlv** [comment]
> And that looks really amazing but is only limited to that terminal emulator and has no backwards compatibility at all as I am aware of.

I have worked quite a bit on Kitty as well, mostly on its graphics stuff, and you are wrong. Every effort has been made to make the spec implementable on other terminals. Someone just has to do so. The [doc](https://sw.kovidgoyal.net/kitty/graphics-protocol.html#querying-support-and-available-transmission-mediums) is clear on this (I wrote this section):

> While as of May 2020, kitty is the only terminal emulator to support this graphics protocol, we intend that any terminal emulator that wishes to support it can. To check if a terminal emulator supports the graphics protocol the best way is to send the above query action followed by a request for the primary device attributes. If you get back an answer for the device attributes without getting back an answer for the query action the terminal emulator does not support the graphics protocol.
>
> This means that terminal emulators that support the graphics protocol, must reply to query actions immediately without processing other input. Most terminal emulators handle input in a FIFO manner, anyway.
>
> So for example, you could send:
>
>```<ESC>_Gi=31,s=1,v=1,a=q,t=d,f=24;AAAA<ESC>\<ESC>[c```
>
>If you get back a response to the graphics query, the terminal emulator supports the protocol, if you get back a response to the device attributes query without a response to the graphics query, it does not.

---

> **Ah, maybe also think about creating and adding a link to some IRC or Matrix community to the README so that people could discuss a bit about SIXEL (so they don't need to spam issues.. Lol).**

I just joined and registered #libsixel on irc.libera.chat.

> 09:22:17 -- ChanServ (ChanServ@services.libera.chat): #libsixel is now registered to copypaste.

**Comment by ctrlcctrlv** [comment]
@kovidgoyal would know more about implementing Kitty graphics in other terminals. If you're actually curious how to do it, I don't think it'd be that hard. There are libraries in various languages already for Kitty graphics. Kitty graphics are the best, I just work on Sixel because there's a lot of software that's never upgrading, and also it's better supported in other terminals including hardware terminals so it's a more well-worn standard. Also, a lot of terminals have already decided for various reasons not to pick up the Kitty graphics standard, mostly for what I think are ignorant reasons (they think they have to pick up the whole spec including the shared POSIX memory, they don't).

**Comment by schrmh** [comment]
Ah, okay. I guess I forgot about that part since it has been a while since I tried kitty (and the only thing I remembered was that it was kinda slow at that time on my machine). But yeah, my personal opinion is that SIXEL has a lot potential since it already has many implementions (even tho they could be improved), which you kinda also wrote with your second reply to my last message.

**Comment by ctrlcctrlv** [comment]
In some ways Sixel graphics are also easier to implement as long as you're using an open source encoder/decoder. It's a much smaller spec without things like z-indexes, image resizing, image ID tracking, full alpha, animations…I see why a lot of people reach for Sixels if they want to add graphics to a terminal application. All Sixel graphics immediately appear "here" right where the cursor is, and can be saved easily in files. I think actually the standards solve different purposes, and terminal emulators should support both.

Like for example let's say you have an app where user is scrolling around. You have to keep re-sending the Sixel graphic on every scroll. If you have many graphics like in `elinks` as I've been testing, that can be slow, even in `xterm`, not to mention a real terminal. Kitty, meanwhile, persists graphics, so it can just continuously call redraw with a known graphic ID.

**Comment by kovidgoyal** [comment]
Indeed, I designed kitty's protocol to be a good fit for rendering with modern approaches, on the GPU. So it should be fairly easy to implement in terminal emulators that have a reasonably modern graphics pipeline. For instance, the entire thing (apart form parsing the escape code, the disk cache and the shader) is implemented in less than 2K lines of C code (graphics.c) in kitty. All told probably less than 5K lines of code.

**Comment by dankamongmen** [comment]
> Ah, okay. I guess I forgot about that part since it has been a while since I tried kitty (and the only thing I remembered was that it was kinda slow at that time on my machine). But yeah, my personal opinion is that SIXEL has a lot potential since it already has many implementions (even tho they could be improved), which you kinda also wrote with your second reply to my last message.

@schrmh , if you want to portably drive both formats, i recommend my own [Notcurses](https://github.com/dankamongmen/notcurses). it is currently using its own sixel encoder, but i hope to move to libsixel in the near future. it provides an abstraction over each.

**Comment by schrmh** [comment]
@dankamongmen I found out about notcurses last week but it also suffers from different kind of sixel implementations. Also it doesn't make use of sixels when I use [st-sixel](https://github.com/galatolofederico/st-sixel) (tho even the popular [lsix](https://github.com/hackerb9/lsix) claims that the patched st doesn't support sixel even tho it does)

**Comment by dankamongmen** [comment]
> @dankamongmen I found out about notcurses last week but it also seems to suffers from different kind of sixel implementations (e.g. the dolphin that can be seen after running `notcurses-demo` doesn't move in mlterm; looks fine in xterm but is slow). Also it doesn't make use of sixels when I use [st-sixel](https://github.com/galatolofederico/st-sixel) (tho even the popular [lsix](https://github.com/hackerb9/lsix) claims that the patched st doesn't support sixel even tho it does)

i've never played with st-sixel (why does `st` have so many forks?), but i'm happy to add support. i assure you notcurses drives sixel =]. i'd much appreciate you filing a notcurses bug (https://github.com/dankamongmen/notcurses/issues/new/choose) with details -- let's not disrupt this issue =].
