### ISSUE TITLE
Organization logo

### ISSUE THREAD

**Issue by ctrlcctrlv** [libsixel/libsixel#18]
This conversation is spun out of #17.

@schrmh thought the current organization logo, which I drew to replace the default which looked like a creepy pixelated happy face, was too history-oriented.

![image](https://user-images.githubusercontent.com/838783/121918694-4e2bf900-cd04-11eb-8417-aa755f209065.png)

So I have a new version:

![image](https://user-images.githubusercontent.com/838783/121919741-533d7800-cd05-11eb-9f19-069322672d23.png)

Is this better? If so I can replace it.

**Comment by prettykool** [comment]
Jesus Christ, I've seen illuminated medieval manuscripts less complicated than these designs. I respect the intention behind them, but, as logos for an organization, they both have *too much* going on to, in my opinion, be suitable. 

I decided to make this alternative thing, taking the motif of that red-and-white checkered rectangle and putting it on a blue background with a gray border. It's not much, but hey, it's fairly memorable, and recognizable. 

![image](https://user-images.githubusercontent.com/79608594/121922378-8977f900-ccff-11eb-8f95-e423ffd24c67.png)

...and here it is at the original resolution (`14x14`)

![image](https://user-images.githubusercontent.com/79608594/121922963-102cd600-cd00-11eb-811c-caaa30dd2116.png)

**Comment by ctrlcctrlv** [comment]
Open source has certain design language. You wouldn't understand. ;-)

![image](https://user-images.githubusercontent.com/838783/121923535-08bdfa80-cd09-11eb-84a1-79b6a2ff139b.png)
![image](https://user-images.githubusercontent.com/838783/121923612-1bd0ca80-cd09-11eb-8b08-3336cb00db66.png)
![image](https://user-images.githubusercontent.com/838783/121923729-37d46c00-cd09-11eb-942f-7b8750cee5d6.png)
![image](https://user-images.githubusercontent.com/838783/121924004-7ec26180-cd09-11eb-923b-496964ab29ff.png)
![image](https://user-images.githubusercontent.com/838783/121924355-d19c1900-cd09-11eb-86ca-1de3346a5d22.png)

I don't like over-simple logos. It's not a shoe. We're trying to say what it does.

I like how `libpng` logo, PNG spec reference implemetation, shows all the features of PNG:

![image](https://user-images.githubusercontent.com/838783/121924143-a1ed1100-cd09-11eb-883f-ce003c7716da.png)

**Comment by ctrlcctrlv** [comment]
Also I should say even though this is the organization logo, the organization is just the user that holds the repository. So, it's really a logo for libsixel, not the organization. Because the organization isn't going to hold anything that's not libsixel related.
