### ISSUE TITLE
No longer compiles on macOS

### ISSUE THREAD

**Issue by Mic92** [libsixel/libsixel#31]
The original libsixel compiles without [patches](https://formulae.brew.sh/formula/libsixel)

Now we get:

```
Has header "sys/stat.h" : YES 
Has header "fcntl.h" : YES 
Has header "sys/io.h" : NO 

meson.build:129:2: ERROR: Assert failed: Needed header not found
```

Reported here: https://github.com/NixOS/nixpkgs/pull/138445

Apparently macOS uses `sys/uio.h` instead - I don't have this OS to test this.

**Comment by dankamongmen** [comment]
alright, i'll take a look at it. i don't have a mac here to test on, but i think i can get access to one.

**Comment by dankamongmen** [comment]
alright, confirmed the failure on big sur. lemme see what i can do.

**Comment by dankamongmen** [comment]
so i don't see anything actually using sys/io.h, and am inclined to remove it.

after that, on mac, we die with all these `needed_function` arguments, yet build successfully without them. as they're all basic C lib functions (most of them, anyway), and i don't know meson well at all, i'm inclined to remove this section entirely.

**Comment by dankamongmen** [comment]
wanna give current master a spin?

**Comment by Mic92** [comment]
Thanks. Even works on aarch64-linux now!

**Comment by dankamongmen** [comment]
if you need, i can cut 1.10.2, but i'd just as soon hold off if you've got a working solution (presumably via a patch).

**Comment by Mic92** [comment]
Yes. I just backported the patch at the moment: https://github.com/NixOS/nixpkgs/commit/86682241081f7e291b8df454f60c0200b7f26050
However once 1.10.2 is out I can drop this again and our update bot will be able to update future versions automatically.

**Comment by dankamongmen** [comment]
awesome! i assume you're a NixOS maintainer? i'm the author of Notcurses, and i'm looking for a NixOS maintainer, where we're substantially behind:

https://github.com/dankamongmen/notcurses/issues/2193

if you'd be willing to pick it up, i'd be in your debt!

**Comment by dankamongmen** [comment]
i've even got a PR outstanding to go to 2.4.0 https://github.com/NixOS/nixpkgs/pull/133203

**Comment by Mic92** [comment]
fixed.
