### ISSUE TITLE
Add SONAME Versioning

### ISSUE THREAD

**Issue by cinerea0** [libsixel/libsixel#37]
Currently the `libsixel.so` library generated by this repo is unversioned. It would be very helpful for distros that are trying to move away from the original libsixel to this fork if versioning could be implemented.

**Comment by dankamongmen** [comment]
great call, thanks. i'll get this done pronto.

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ objdump -p src/libsixel.so | grep SONAME
  SONAME               libsixel.so
[schwarzgerat](0) $ 
```

yeah let's get a 1 on there

**Comment by dankamongmen** [comment]
i think simply defining the abi version will get this

**Comment by dankamongmen** [comment]
```sh
[schwarzgerat](0) $ objdump -p src/libsixel.so | grep SONAME
  SONAME               libsixel.so.1
[schwarzgerat](0) $ 
```

yay
