### ISSUE TITLE
get proper cflags

### ISSUE THREAD

**Issue by dankamongmen** [libsixel/libsixel#43]
if we're compiling with e.g. libgdk-pixbuf-2.0, we need:

```sh
[schwarzgerat](1) $ pkg-config --cflags gdk-pixbuf-2.0
-I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -pthread -I/usr/include/libmount -I/usr/include/blkid 
[schwarzgerat](0) $ 
```

i guess we get to learn a new build system tonight unless we want ci broken

**Comment by dankamongmen** [comment]
@ctrlcctrlv , you're the one who rewrote this in meson; any chance you can handle this?

**Comment by ctrlcctrlv** [comment]
@dankamongmen Sorry for the delay, could've handled it had you had more time to wait. Sorry.

**Comment by dankamongmen** [comment]
> @dankamongmen Sorry for the delay, could've handled it had you had more time to wait. Sorry.

np, eli got it fixed up right away =]
